theme: jekyll-theme-cayman
show_downloads: true
url: "https://dtu-pas.github.io/RumexLeaves/"
title: RumexLeaves
description: >- # this means to ignore newlines until "baseurl:"
  RumexLeaves contains in total 809 images with 7747 annotations of Rumex obtusifolius leaves. For each leaf, a pixel-wise leaf blade annotation as well as a polyline annotation of the stem - if visible - and vein were manually created. 
  The stem is visible for ~ 45% of the leaves. We differentiate between two variants of datapoints: (1) iNaturalist datapoints that have been downloaded from the plant publisher iNaturalist and (2) RoboRumex datapoints collected with an
   agriculture robotics platform. Both variants originate from real-world settings.
github:
  zip_url: https://github.com/DTU-PAS/RumexLeaves
