theme: jekyll-theme-cayman
show_downloads: true
url: "https://dtu-pas.github.io/RumexLeaves/"
title: RumexLeaves
description: >- # this means to ignore newlines until "baseurl:"
  RumexLeaves is a image dataset with fine-grained annotation of Rumex obtusifolius weeds. For each indivudal leaf, we provide a pixel-level segmentation mask as well as a keypoint-guided polyline along stem and major vein of the leaf. The dataset includes 809 images with 7747 annotations, while it is differntiated between two types of datapoints: (1) iNaturalist datapoints have been downloaded from the plant publisher iNaturalist and (2) RoboRumex that have been collected with a Husky Robot platform. Both variants originate from real-world settings. The following table gives an overview of the dataset.

github:
  zip_url: https://data.dtu.dk/ndownloader/files/41521812
